apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: ${REPOSITORY}
    context: ./
    docker:
      dockerfile: ./Dockerfile
deploy:
  kubectl:
    manifests:
    - ./deploy-frontend.yaml